"""Lossless clean: pixels unchanged, coded scan / IDAT unchanged, metadata gone."""
from __future__ import annotations

import hashlib
import io
from pathlib import Path

import pytest
from PIL import Image, PngImagePlugin

import split_grids as sg


def _jpeg_scan(data: bytes) -> bytes:
    """Entropy-coded scan (from SOS marker to end)."""
    i, n = 2, len(data)
    while i < n - 1:
        if data[i] != 0xFF:
            i += 1
            continue
        m = data[i + 1]
        if m == 0xDA:
            return data[i:]
        if m in (0xD8, 0x01) or 0xD0 <= m <= 0xD7 or m == 0xFF:
            i += 2 if m != 0xFF else 1
            continue
        if m in (0xD9,):
            break
        if i + 4 > n:
            break
        seg = int.from_bytes(data[i + 2:i + 4], "big")
        i += 2 + seg
    raise AssertionError("no SOS in JPEG")


def _png_idat(data: bytes) -> bytes:
    out = b""
    for ctype, off, total in sg.iter_png_chunks(data):
        if ctype == b"IDAT":
            length = int.from_bytes(data[off:off + 4], "big")
            out += data[off + 8:off + 8 + length]
    assert out, "no IDAT"
    return out


def _pixels(path: Path) -> bytes:
    with Image.open(path) as im:
        return Image.frombytes(im.mode, im.size, im.tobytes()).tobytes()


def test_jpeg_lossless(tmp_path):
    src = tmp_path / "in.jpg"
    dst = tmp_path / "out.jpg"
    img = Image.new("RGB", (64, 48), (40, 90, 180))
    # APP1-shaped EXIF via Pillow
    exif = img.getexif()
    exif[271] = "TestMake"
    img.save(src, format="JPEG", quality=90, exif=exif)
    before = src.read_bytes()
    assert sg.inspect_image_metadata(src), "expected metadata in source"

    res = sg.clean_image_file(src, dst)
    assert "lossless" in res["mode"]
    after = dst.read_bytes()
    assert _pixels(src) == _pixels(dst)
    assert hashlib.sha256(_jpeg_scan(before)).digest() == hashlib.sha256(_jpeg_scan(after)).digest()
    leftover = [f for f in sg.inspect_image_metadata(dst)
                if f.label.startswith("APP") or f.label.startswith("COM")]
    assert leftover == []


def test_png_lossless(tmp_path):
    src = tmp_path / "in.png"
    dst = tmp_path / "out.png"
    img = Image.new("RGB", (40, 30), (10, 200, 40))
    info = PngImagePlugin.PngInfo()
    info.add_text("Comment", "generated by a test")
    img.save(src, format="PNG", pnginfo=info)
    before = src.read_bytes()
    assert any("tEXt" in f.label or "text" in f.label.lower() or "Comment" in f.detail
               for f in sg.inspect_image_metadata(src)) or sg.inspect_image_metadata(src)

    res = sg.clean_image_file(src, dst)
    assert "lossless" in res["mode"]
    after = dst.read_bytes()
    assert _pixels(src) == _pixels(dst)
    assert hashlib.sha256(_png_idat(before)).digest() == hashlib.sha256(_png_idat(after)).digest()
    meta = [f for f in sg.inspect_image_metadata(dst)
            if f.kind in ("chunk", "segment") and "IDAT" not in f.label]
    # keep-chunks like gAMA/sRGB may remain; drop text/exif
    assert not any(x in "".join(f.label for f in meta) for x in ("tEXt", "eXIf", "iTXt", "zTXt"))


def test_webp_pixels(tmp_path):
    src = tmp_path / "in.webp"
    dst = tmp_path / "out.webp"
    img = Image.new("RGB", (36, 28), (200, 20, 20))
    img.save(src, format="WEBP", lossless=True, exif=b"Exif\x00\x00" + b"\x00" * 16)
    res = sg.clean_image_file(src, dst)
    assert "lossless" in res["mode"]
    assert _pixels(src) == _pixels(dst)
    leftover = sg.inspect_image_metadata(dst)
    assert not any("EXIF" in f.label or "XMP" in f.label for f in leftover)
